{% set name = "seqan-library" %}
{% set version = "1.4.2" %}
{% set sha256 = "004e6e07ec2e137cc5f637372ea9f67156066ee8a88a583f37490741bd31045e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://github.com/seqan/seqan/releases/download/seqan-v{{ version }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  script: cp -r include share $PREFIX  # [unix]

test:
  commands:
    - test -f $PREFIX/include/seqan/seq_io.h  # [unix]
    - if not exist "%PREFIX%"\\include\\seqan\\seq_io.h exit 1  # [win]

about:
  home: https://www.seqan.de
  license: BSD-3-Clause
  license_file: share/doc/seqan/LICENSE
  summary: 'SeqAn is a C++ library for the analysis of biological sequence data.'
  description: |
    SeqAn contains a header only library and some associated tools.
    This package does *not* contain those tools, but only the library
    (the files in `include` and `share`).
  dev_url: https://github.com/seqan/seqan

extra:
  recipe-maintainers:
    - aseyboldt
