travis:
  secure:
    BINSTAR_TOKEN: aYpI1hUAqybTsp8R5lvabD4X8ZGMPkpkbuuq23HqmC0CyQY+dPK7DmjIo8jzmYnQK6Sic7nQaUFVPWgmYvZm97km/NTG1qcEsog9jPXq2fT/HtDDuekCXVDlieHVp3oImGi4KfPz1wHa1we1kGQoYhYu6cTYNgM7FofKs/xnsrH2iop0qF/Yc+2LzbCdvDbchC09rZhU7G8s1uf+XwcEqjzvsoFV+4HrwOklte6Ddg9Kco5EPf6j7P5T46kTlhZ+AOcS5QQwSYRtbkrLZXvjgKEQZ5aZzr0bHvFxREwIj4CGKIcY2r+GNBZqOQuKD4eaBgUK9K0BGDWmQuHTJmHz4HHyZzfX7Ps5DmeHudiCRpm7upkD9dk1qlfqrrTjVxb7mZZZHzQMqrEYl32cPbmr6Qpn7p8mgimH2DF8MNLATdjU8bVvGTAD4Doideu/wq0sha8Brpq4xY1GIM84tyTBSYTvb28THqqkPY7SmMMFEq1O8XJrP+5FSTW4QtKVSTk1+ghRkOfr7nhNZYh7HOYBJIi6MKR3bsDVtyUZvENlgK5N298hYykwHIDO8FcWAu7tthyFUCz0WjV0HkysUE2+GtSz02gR/v0lXXB3x1c88QfkFdU8YNqThm5edZbm2J2Th8xEZbj6sfB451rK3kqcYnvN2Ehn2oiiJUo5Cd6OlDM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
